### ISSUE TITLE
Flatbuffers dependency long-term?

### ISSUE THREAD

**Issue by quinnj** [wesm/feather#160]
Digging into the source, it made me wonder if the plan is to keep flatbuffers as a dependency long-term, or to define a kind of "standard metadata layout", similar to what's already been done for array layouts. It doesn't seem like there's anything crazy in the metadata section/storage, so just wondering if I'm missing some other kind of benefit from flatbuffers or if it's been viewed as a more short-term solution anyway.

**Comment by wesm** [comment]
From my perspective, I don't see what would stand to be gained from bespoke metadata serialization (since the memory layout of the metadata does not have a meaningful impact on performance or interoperability), and making changes to the metadata would become much more complex. Flatbuffers also helps with schema evolution (i.e. new fields can be added without breaking existing files), though we aren't yet at a point where we're guaranteeing that old files will be readable in the future.

**Comment by quinnj** [comment]
Thanks for the response. I see the benefits of using flatbuffers as a "black box" for storing metadata (though there's obviously still ways to spec out a memory layout as a dictionary to say "continue reading key-value pairs in this region" that would handle new future metadata fields).

I was mainly interested in hearing if you were planning on this dependency long-term or not.
