### ISSUE TITLE
Invite JS to the party?

### ISSUE THREAD

**Issue by hadley** [wesm/feather#17]
Would obviously need a completely different codebase, but it would be useful for (e.g.) ggvis

**Comment by kokes** [comment]
Flatbuffers [have a JavaScript implementation](https://github.com/google/flatbuffers/blob/master/js/flatbuffers.js), most of the numerical arrays are supported natively as [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays), but sorting out (u)int64 will probably be the trickiest part. I think you (wes) have mentioned this in [your datapad talk](https://www.youtube.com/watch?v=wPEmoT018s8), if I remember correctly. Did you end up sorting this out in some way?

Either way, I'm on board with this, because I've recently [tried](https://github.com/kokes/smda) in-browser parsing of medium-sized CSVs (~150 megs) and the large memory consumption in Chrome together with a slow GC just makes this unusable. A direct byte-by-byte access in feather would make my life a lot easier, assuming there's no further overhead of this direct read.
And this use case would probably make for a nice side by side comparison of memory usage (as well as speed) in a data-intenstive web app. (Though I presume people would argue that a backend with an API is more suitable for data heavy work in the browser.)

**Comment by dragoljub** [comment]
I could see this being a win for passing bigger data sets between Python and BokehJS more efficiently.

**Comment by cscheid** [comment]
I'd love to use this (and volunteer to take a stab at a basic JS API). I foresee this being quite efficient with [ArrayBufferView](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView)s. Currently it's possible for XHR return values to be a binary blob. The API gives you an ArrayBuffer, from which you can directly get typed array buffer views, and no-copy typed arrays.

However, there's an issue of alignment that comes up. It bit me in the past with [rserve-js](http://github.com/cscheid/rserve-js), so I think it's worth thinking about more carefully. In JS typed arrays, views must be aligned at element boundaries of the array buffer. 

So if I understand the current binary format correctly, it's impossible to do no-copy float64 at the Array 0 position from a XHR'ed feather file, because it starts at offset 4.

I'd like to request the Feather binary format to be 8-byte aligned at array boundaries (I actually think you'll want to future-proof the API by specifying the alignment at the next 4 bytes, and promising a minimum of 8-byte alignment. But this is overengineering at this point). With 8-byte array boundary alignment, we would be able to do no-copy views of all currently supported JS typed array primitive types: uint8, uint16, uint32, float32, and float64. These could go straight into the GPU via WebGL, so my mind is swimming with sweet demos :)

Is a change on the format still feasible at this point?

**Comment by ScottPJones** [comment]
Is that part of the format fixed by following Apache Arrow? (the alignment on array boundaries)?  If not, it might be nice to go a bit further, and have 16-byte alignment, or even higher, such as 64-byte alignment, if that's not seen as too much overhead (to allow for cache-line alignment on many processors).  (16-byte alignment would be needed for handling Julia's `Int128`/`UInt128`, or for the IEEE 754-2008 128-bit decimal floating point format, for example, if the spec were extended to allow for those).

**Comment by wesm** [comment]
We're actually talking right now on the Arrow mailing list about 64-byte alignment to be able to support AVX-512bit SIMD operations in the future. So we can definitely change the Feather format to allow for this.

**Comment by wesm** [comment]
Right now, in fact, we are having to make our first breaking change because of #108. I'm going to add a version number to the format as some changes to the format will be backwards compatible while others not. At some point we may be able to guarantee format stability on some horizon (or at least provide graceful upgrades (e.g. v2 -> v3, but we then remove the v2->v3 adapter code after a period of time).

**Comment by cscheid** [comment]
64-byte alignment is also cache line alignment for a variety of architectures, right? I think that's a very good idea for feather.

**Comment by ScottPJones** [comment]
It's not for POWER, which has 128-byte cache lines, but I'm afraid that might simply be too much alignment for some cases.  Is it something that could indicated in the header? (8, 16, 32, 64, 128 etc. alignment?)  About #108, could provision be made in the metadata for arbitrary bases (like Fortran 90, or what is being discussed currently for Julia)?

**Comment by KrishnaPG** [comment]
Wondering the state of this? Is there some JS client that can consume data produced by R?

If not done yet, would greatly appreciate if the JS implementation is made possible to work from browser also (not just node.js). Reading data produced by R in Feather format over ajax in browser by JS could be very valuable.

**Comment by wesm** [comment]
We would gladly welcome a JS implementation to be contributed to the project. We added the word padding to make a JS/node implementation easier.

**Comment by cscheid** [comment]
I have a half-broken implementation (it's essentially trivial). The current problem right now is reading the metadata appropriately - I would really like to be able to do this without referring to a Javascript implementation of FlatBuffers.

**Comment by wesm** [comment]
Work has commence on a JS (TypeScript) implementation of Apache Arrow, which is the best path forward here: https://github.com/apache/arrow/tree/master/js
