### ISSUE TITLE
Add functionality to go directly from flat file to feather file

### ISSUE THREAD

**Issue by dermcnor** [wesm/feather#175]
It would be nice, mostly when you have a really large file to be able to straight from a flat file to a feather file and skip the step of importing (e.g. read.csv) to a data.frame.  If this were possible, then you could operate on quite large files (larger than available RAM?) and use the current subsetting capabilities to operate on manageable chunks from the file.

**Comment by quinnj** [comment]
I'll let @wesm and @hadley comment further, but I'm not sure there's really an easier way to go from a CSV, for example, to a feather file format. The problem is that the feather file format is encoding things directly like type information, # of rows, and then directly serializing binary values. What this means is you basically have to "parse" the CSV file anyway to go from text to actual values before writing out to the feather format, so you pretty much have to do everything a CSV parser is doing anyway.

That said, https://github.com/wesm/feather/issues/8 would allow you to append to an existing feather file, so you could still have the ability to read a flat file in chunks, appending to the feather output, which would allow for less pressure on memory.

**Comment by wesm** [comment]
I'd be interested in evolving the Feather writer and metadata to permit multiple chunks (assuming that the schemas are compatible). Appending to an existing file would be doable hypothetically (though quite a bit of engineering work)

**Comment by benitocm** [comment]
Hi,

This functionality will allow to concat dataframea In this keeping the schema right?

**Comment by benitocm** [comment]
Hi,

This functionality will allow to concat dataframes in disk and  keeping  the schema right?

Sorry for the typo

**Comment by wesm** [comment]
That's the idea. I'm not sure about appending to existing files, but you might be able to create a file in multiple chunks rather than having to have all of the data materialized in memory.

**Comment by benitocm** [comment]
Currently, is there any way to create a feather file whose dataframe does not fit in memory?
Thanks

**Comment by Bernolt** [comment]
Is there any improvement on that topic?

**Comment by wesm** [comment]
This work is planned in the Apache Arrow project and can be undertaken as soon as we can ship R bindings. You can help it go faster by getting involved with the Arrow project

**Comment by wesm** [comment]
In Feather V2 (coming in Arrow 0.17.0) we use the Arrow IPC file format which uses incremental writes, so memory constrained file writes are possible there. Feel free to open a JIRA issue in Apache Arrow and we can consider APIs for incremental Feather file building
