### ISSUE TITLE
Why not Parquet?

### ISSUE THREAD

**Issue by mpouttuclarke** [wesm/feather#188]
I don't understand why we are creating yet another data format.  Parquet has a C++ binding so why not just add some syntactic sugar to support Python, R and others?  
https://github.com/Parquet/parquet-cpp

**Comment by wesm** [comment]
Parquet's C++ library is now hosted here now: https://github.com/apache/parquet-cpp (note: I am an Apache Parquet committer).

When considering data formats, you must consider:

- what kind of data is being stored? 
- what are the usage patterns for that data?

I argue that Feather and Parquet have slightly different answers to these two questions. Several points

- One obvious issue is Parquet's lack of built-in support for categorical data. This means pandas's categoricals and R's factors

- Parquet is optimized for IO constrained, scan-oriented use cases. For example: if you have an IO subsystem that can only give you 200 MB/s (e.g. spinning rust hard drives), then Parquet is great because the encoding and compression strikes a balance between smallness and speed to decompress. Feather, on the other hand, assumes that IO bandwidth is not as much of an issue. Parquet theoretically will outperform with highly compressible/encodable data (the C++ Parquet library is still a work-in-progress, so we haven't done in-depth perf analysis)

- Parquet does not support random access / reads from the middle (again, due to the emphasis on scan workloads found in SQL engines or Spark). The hope is that Feather may be able to help with multithreaded / out-of-core workloads someday, and this is a useful feature.

Those are the things on the top of my head. In summary: adding syntactic sugar on top of Parquet will not easily provide an adequate solution.

**Comment by xhochy** [comment]
@wesm can you add that to the README/some other documentation? The question will definitely come up more often.

**Comment by richierocks** [comment]
If you are documenting "why we used this technology not that", you might also want to add a section on why you didn't use HDF5, since that's a common cross-platform data storage format.

**Comment by wesm** [comment]
@richierocks sure, you are not the first person to ask. The thing about HDF5 is that the only value it would provide in this case would be taking responsibility for the location (and the reading and writing) of blobs of bytes in the file, which is the simplest part of the problem. A Feather file internally is a data stream (a concatenation of table columns) followed by a compact chunk of metadata describing the layout of the file. HDF5 does not provide this metadata support.

**Comment by mpouttuclarke** [comment]
@wesm:  Thanks for the quick response.  So with regards to Parquet's lack of support for categorical data, parquet-avro resolves that right?

The point about random access is well taken.  However I would resolve that by storing flatbuffer key values in leveldb or some other key value store.  

I like that there is no dependency on HDFS as that is a legacy technology already as network attached block storage already does a better job than HDFS.  Hard dependency on Hadoop is an annoyance in Parquet I could do without.

**Comment by mpouttuclarke** [comment]
The reason for the question is that the "big data" area is as flooded with data formats as it is with hype.  We really don't need more unless there is a really good reason for it.  Otherwise it just creates more FUD

**Comment by wesm** [comment]
@mpouttuclarke No, I do not think parquet-avro helps. The intent of parquet-avro, parquet-thrift, etc. is to provide a mechanism to map those IDL / schema specifications onto Parquet files (read and write). For example, there are systems (think: streaming data collectors which store things as Parquet files) where data needs to be received in Thrift / Avro format (e.g. log messages). 

I agree that it is sometimes difficult for people who are not experts in these technologies to tell them apart / decide which one to use. If you require a specialized solution for a real world use case (for example, as we have done here), your technical decisions should not be driven by the possible confusion that it will cause laypeople / casual observers. Be wary of the Highlander Fallacy (http://www.artima.com/weblogs/viewpost.jsp?thread=202304).

**Comment by hadley** [comment]
I don't think this causes much confusion amongst the primary users of feather - in my mind, these are regular people who are using python and R for data analysis, and want a file format that is better than csv.  None of the other file formats come anywhere close to supporting this group of users.

**Comment by mpouttuclarke** [comment]
Got it.  Not trying to be a buzzkill but I really think you guys need to put down on paper exactly why and where this format should be used and where you see it fits in the big data landscape.  It isn't enough to just invoke being an Apache or R committer.  A tool is only good when used as designed, and with 20+ years dealing with customers using a screwdriver when a hammer is needed the help would be appreciated :)

**Comment by kaybenleroll** [comment]
As one of the intended audience of feather in both R and Python I can
attest to having no ambiguity at all to what problem they are solving. :)

Feather is pretty much the solution.

And I don't think it fits at all into the "Big Data" landscape. It appears
to be aimed squarely at the "one machine - do some analysis" space.
On 13 Jun 2016 20:23, "Matt Pouttu-Clarke" <notifications@github.com> wrote:

Got it. Not trying to be a buzzkill but I really think you guys need to put
down on paper exactly why and where this format should be used and where
you see it fits in the big data landscape. It isn't enough to just invoke
being an Apache or R committer. A tool is only good when used as designed,
and with 20+ years dealing with customers using a screwdriver when a hammer
is needed the help would be appreciated :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/wesm/feather/issues/188#issuecomment-225681576>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAzaOBTJbHI6EOWoR1tvI3Bv075hsBKvks5qLa42gaJpZM4Iz3Ub>
.

**Comment by mpouttuclarke** [comment]
As soon as Arrow is mentioned you are in the big data landscape, like it or not.  People creating little data islands using a divergent format in a 100 billion company for example is not cool.  Unless of course there are very good *specific* reasons to do so.

**Comment by wesm** [comment]
I'm locking this thread. It's not a good use of anyone's time.
