### ISSUE TITLE
Mangled file names

### ISSUE THREAD

**Issue by FigiMon** [wesm/feather#209]
There seems to be a problem with writing feathers to files in which the file name contains non-ascii characters.

import feather
import pandas as pd

df = pd.DataFrame({'a': [1,2,3], 'b': ['a','b',None]})
feather.write_dataframe(df, "d:/Besa Kavajë.feather")

produces the file
Besa KavajÃ«.feather
which cannot be read back into Python

At the same time
df.to_csv("d:/Besa Kavajë.csv")

gives the file
Besa Kavajë.csv

and similarly
with open("d:/Besa Kavajë.txt", "w") as text_file:
    text_file.write("Test: %s" % 1000)

gives the file
Besa Kavajë.txt

No problem with putting this particular string **into** the dataframe/feather itself, just not in the **file name**.

**Comment by wesm** [comment]
This is sadly a Windows problem. Windows unicode file names have to be encoded (as I am learning from googling) as `utf-16le`. Any chance you can help prepare a patch? I just did a bunch of work on the filesystem C standard library calls to account for differences between windows and POSIX systems. Fun times

**Comment by hadley** [comment]
@kevinushey any insights here?

**Comment by kevinushey** [comment]
Not really, since I'm not that familiar with the Python APIs here, unfortunately.

For R, only strings representable in the system encoding can be safely used on. On systems that default to UTF-8 locales this is not an issue; on Windows where most locales are not UTF-8 this causes problems as the re-encoding of a UTF-8 string to the system encoding is often lossy.

All I know is that, at least at the C level on Windows, you need to convert your strings to a UTF-16le representation, and then call the 'wide' versions of Windows APIs (usually suffixed with a `W`). I'm not sure if the Python system call wrappers do this by default for the user, or if one needs to explicitly re-encode the string as UTF-8 or UTF-16 before performing a system call.

It looks like you can explicitly re-encode strings with e.g. `"foobar".encode("utf-16le")`, so maybe doing that on Windows for paths will be sufficient?

**Comment by FigiMon** [comment]
OK, I was afraid that was the case and also sorry to say that I wouldn't know where to begin in terms of a patch. I would be more than happy to help with testing and simpler stuff if needed though.

**Comment by kevinushey** [comment]
@FigiMon, what happens if you explicitly re-encode the paths before passing them to the feather APIs? E.g.

```
feather.write_dataframe(df, "d:/Besa Kavajë.feather".encode("utf-16le"))
```

**Comment by FigiMon** [comment]
That only writes the first character of the path/filename. In my example it writes a file named "d" to the hdd.

However re-encoding with sys.getfilesystemencoding() does work:

feather.write_dataframe(df, "d:/Besa Kavajë.feather".encode(sys.getfilesystemencoding()))
produces the file
Besa Kavajë.feather
which is correct

**Comment by FigiMon** [comment]
In R everything seems to work without re-encoding though
````
write_feather(df, '~/Besa Kavajë.feather')
````
gives me a file
````
Besa Kavajë.feather
````
and also
````
read_feather('~/Besa Kavajë.feather')

# A tibble: 3 x 2
      a     b
  <dbl> <chr>
1     1     a
2     2     b
3     3  <NA>
````

**Comment by wesm** [comment]
@figimon are you using git master? These code paths have changed significantly. 

On Windows I believe we will need to use `_wsopen_s` for utf-16le file names

**Comment by FigiMon** [comment]
I am using the version from conda-forge
````
feather-format            0.2.0.post007+g36c328e          py35_0    dhirschfeld
````

**Comment by wesm** [comment]
Got it. I will try to find time to debug -- if any Windows-based developers are reading your help on this would be appreciated. Thank you

**Comment by wesm** [comment]
this is fixed in master now -- with some luck we will get a feather release out in the next week or two to CRAN and conda-forge

**Comment by FigiMon** [comment]
Great, thanks very much!
