### ISSUE TITLE
Feather IO subsystem behaves improperly when the user attempts to overwrite an existing file

### ISSUE THREAD

**Issue by wesm** [wesm/feather#249]
Files are not being truncated to 0 bytes before being written if they already exist -- this will cause corrupted metadata in a lot of cases if the data written is smaller than the original file (because the writes still happen from the beginning of the file).

There are already a lot of bug reports (#248, ...) that are caused by this problem. We should fix and make a bugfix release as soon as practical

**Comment by simonbrownsb** [comment]
I'm coming across this problem a lot too. In most cases it's crashing with a SIGSEGV, not just 'failing'.

Only happens if the newly-saved dataframe is smaller than the previous one Presumably the file isn't being opened for writing with O_TRUNC (and therefore junk is being left at the end, after writing out the new contents).
