### ISSUE TITLE
cannot serialise column of all nan's - in Python

### ISSUE THREAD

**Issue by CommodTrader** [wesm/feather#295]
I am writing a pandas dataframe to feather.

Getting the error message '_cannot serialize column 4 named Last with dtype floating_'.
It seems to be able to handle a column with some nan's, but here the column is all nan's and it is falling over.

Is there a workaround, am I doing something wrong, or is it a bug?

**Comment by wesm** [comment]
The error AFAICT you're getting is because of a column with mixed-type objects: https://github.com/wesm/feather/blob/262b3792b1a4f6040c13acf609274faa3a0c296a/python/feather/api.py#L44 -- any more detail about what the data looks like? In the event of an object column with all NaN objects, it should be inferring floating point type

**Comment by CommodTrader** [comment]
I've attached a copy.  It has some entirely blank columns.  First I'm getting the error message Invalid: Unable to infer type of object array, were all null.  And then its failing to serialise, when it should be inferring floating.  My fix has been to replace all the nan's with None in empty columns.

[Copy of GOF2016.xlsx](https://github.com/wesm/feather/files/909429/Copy.of.GOF2016.xlsx)

**Comment by wesm** [comment]
Thanks. Since we moved the Feather implementation to the Arrow codebase, errors like these will be easier to fix. I plan to do a Feather 0.4 release depending on pyarrow (with some new features / performance improvements) in the next month or so

**Comment by CommodTrader** [comment]
Great - look forward to it

**Comment by wesm** [comment]
This is fixed in Feather 0.4
