### ISSUE TITLE
Tibble with Date column is not identical to itself after writing and reading with feather

### ISSUE THREAD

**Issue by amarchin** [wesm/feather#313]
Let's consider the tibble

```r
x <- tibble::tibble(start_date = lubridate::ymd(NA, NA, "2016-01-01", "2018-04-01", NA))
```
Obviously it is identical to itself

```r
testthat::expect_identical(x, x)
```

But if i write the file to disk and then I read it then I get an error

```r
library(feather)
write_feather(x, "x.feather")
x_feather <- read_feather("x.feather")
system("rm x.feather")
testthat::expect_identical(x, x_feather)

# Error: `x` not identical to `x_feather`.
# Rows in x but not y: 1. Rows in y but not x: 1. 

```

**Comment by amarchin** [comment]
If I focus on the vector the situation is different

```r
testthat::expect_identical(x$start_date, x_feather$start_date)

# Error: x$start_date not identical to x_feather$start_date.
# Objects equal but not identical
```

**Comment by gansanay** [comment]
What differs is the type of the dates: Feather writes them as integers regardless of their original type.

Here you have dates as double in `x` and as integer in `x_feather`.

Maybe @hadley has some insight about this.

**Comment by hadley** [comment]
They should be coerced to doubles when creating the date object in R. (I was probably confused about this when I wrote the R binding code)

**Comment by gansanay** [comment]
I naively tried to edit `addDateColumn()` to enforce the original type of a date column:

```cpp
Status addDateColumn(std::unique_ptr<TableWriter>& table,
                     const std::string& name, SEXP x) {
  // dates can be stored either as integers or doubles
  if (TYPEOF(x) != INTSXP && TYPEOF(x) != REALSXP)
    stop("%s is corrupt", name);

  auto values = ( TYPEOF(x) == INTSXP ?
    intToPrimitiveArray(Rf_coerceVector(x, INTSXP)) : dblToPrimitiveArray(Rf_coerceVector(x, REALSXP)) );

  return table->AppendDate(name, values);
}
```

but I stumbled upon this part in `src/feather/writer.cc`:

```cpp
Status TableWriter::AppendDate(const std::string& name,
    const PrimitiveArray& values) {

  if (values.type != PrimitiveType::INT32)
    return Status::Invalid("Date values must be INT32");

  ArrayMetadata values_meta;
  AppendPrimitive(values, &values_meta);

  auto meta_builder = metadata_.AddColumn(name);
  meta_builder->SetValues(values_meta);
  meta_builder->SetDate();
  meta_builder->Finish();
  return Status::OK();
}
```

which explicitly states that Timestamps should be integers. As it seemed an intentional restriction, I preferred to ask first before attempting a PR.

**Comment by hadley** [comment]
Timestamps should be integers in feather, but doubles in R.

**Comment by gansanay** [comment]
Ok, this (native type for R timestamps) is the part that was unclear to me.

**Comment by MarcusKlik** [comment]
Hi @Hadley and @gansanay, thanks a lot for providing a nice Apache Arrow implementation for the R community!

A few words on the conversion from `double` to `integer` (and back) with regard to the `Date` type.

On first sight, there seem to be obvious advantages in using the conversion. The resulting vector is half in size and that gives a factor of two more compression of on-disk data. Writing less data also means higher write and read speeds for slow disks. Also when you want to add compression to `feather` later, 
 `integers` can be compressed much more efficiently than `doubles`.

However, because the conversion is happening 'on the `R` side' of the `R` - `Arrow` interface, it's relatively slow:

``` r
Rcpp::sourceCpp(code = '
#include <Rcpp.h>

// [[Rcpp::export]]
SEXP to_integer(SEXP x)
{
    return Rf_coerceVector(x, INTSXP);
}')

dbl_vec <- as.double(1:100000000)  # 800 MB vector

# benchmark of the conversion (100 times)
bench <- microbenchmark::microbenchmark(
  to_integer(dbl_vec)
)

# Speed in GB/s
median(as.numeric(object.size(dbl_vec)) / bench$time)
#> [1] 2.156421
```

That's about 2.15 GB/s on a medium-end laptop (core i7@2.5 GHz). The return conversion is a little slower:

``` r
Rcpp::sourceCpp(code = '
#include <Rcpp.h>

// [[Rcpp::export]]
SEXP to_double(SEXP x)
{
    return Rf_coerceVector(x, REALSXP);
}')

int_vec <- 1:100000000  # 400 MB vector (on-diks size)

# benchmark the back-conversion 100 times
bench <- microbenchmark::microbenchmark(
  to_double(int_vec)
)

# Speed in GB/s (taking the input vector's size)
median(as.numeric(object.size(dbl_vec)) / bench$time)
#> [1] 2.004036
```

So, 2 GB/s on a 800 MB `Date` column. These speeds might seem high but they can bring down the speed of serializing `Date` columns significantly, On estimate the speed of serializing plus a conversion will be:

![image](https://user-images.githubusercontent.com/24658401/30524720-0c1acd38-9bf9-11e7-9e39-33bb813ffd23.png)

(with 2 being the compression factor)

That means that the `double` to `integer` conversion (and vice versa) will only increase speed for disks slower than 1.1 GB/s (write) or 1 GB/s (read), and most modern NMVE SSD's have speeds much higher than that (especially reading).

Also, Apache Arrow is a 'zero-copy' serialization library, which is one of it's strongest features. The type casting breaks that feature, and in-memory copies are made of complete vectors both in writing and reading.

Last but not least, because of the conversion, you can get behavior that might not always be obvious to the non-suspecting user. Taking the mean of a `Date` vector for example can generate fractional `Date`'s, which will be rounded off by the conversion. That behavior, although intended, is different then that of e.q. `saveRDS`, so switching back-ends might introduce errors for the user. Also, the minimum and maximum boundaries of the `Date` type change because of the casting. That's alright for R, but what if the feather file is generated from another language, do those boundaries hold?

Given the points above, perhaps just serializing the `double` vector might be a safer solution, unless there is an important additional reason to convert?

Thanks a lot, just wanted to share my thoughts on the conversion issue and give you something to think about :-)

Can't wait to see how `feather` will evolve in the future!

**Comment by wesm** [comment]
> Given the points above, perhaps just serializing the double vector might be a safer solution, unless there is an important additional reason to convert?

If this ends up being a serious enough bottleneck to merit development energy, we could add Arrow timestamp metadata for values that are stored as a double instead of an int64. This will be easy to experiment with as soon as we have preliminary Rcpp bindings for the Arrow C++ libraries (where Feather's future lies). I stand ready to add more features (multithreaded reads for R, column buffer compression, etc.) but I need the R community to help out with packaging and development lifecycle concerns. The Python version of Feather got significantly faster in many cases after moving to the Arrow codebase.

I will say that timestamps represented as doubles is atypical -- any background on the origin of this choice?

The really interesting future for Arrow in the Python and R worlds will be as a language-agnostic native format for in-memory analytics. So you won't need to convert an Arrow table to an R data frame or pandas data frame, simply evaluate analytics (like dplyr expressions) directly on the Arrow memory (which may live in a memory map or some other virtual memory space / shared memory)

**Comment by MarcusKlik** [comment]
Hi @wesm, thanks for sharing your thoughts. Having _a language-agnostic native format for in-memory analytics_ would be a bright future indeed. But I guess it would also be a challenge to reconcile the fundamentally different underlying types that Arrows's 'client implementations' might have.

For example, the `NA` integer value in `R` (INT_MIN in C++) needs special treatment during analysis and the same holds for the Boolean (which is a 32 bit 3-level value in R). As long as the analytics stay within the Arrow framework, you're alright, but at some point you need logic to convert to different internal formats. It would be great if that conversion could be accommodated by the Arrow framework.

For example, the `Date` conversion code now reads:

``` C++
Status addDateColumn(std::unique_ptr<TableWriter>& table,
                     const std::string& name, SEXP x) {
  // dates can be stored either as integers or doubles
  if (TYPEOF(x) != INTSXP && TYPEOF(x) != REALSXP)
    stop("%s is corrupt", name);
  auto values = intToPrimitiveArray(Rf_coerceVector(x, INTSXP));

  return table->AppendDate(name, values);
}
```

Which means that the type conversion happens in the (single-threaded) `R` world. A flexible solution to that problem might be to adapt the Arrow API in such a way that pre-filtering can be applied from within the framework:

``` C++
Status addDateColumn(std::unique_ptr<TableWriter>& table,
                     const std::string& name, SEXP x) {
  // dates can be stored either as integers or doubles
  if (TYPEOF(x) != INTSXP && TYPEOF(x) != REALSXP)
    stop("%s is corrupt", name);

  DoubleToIntConverter doubleToIntConverter;

  return table->AppendDate(name, x, (PreFilter*) &doubleToIntConverter);
}
```

(or similar). The conversion can then be handled by a multi-threaded (block-wise) implementation in Arrow (preferably in parallel to the IO operations for speed) and different languages can write different custom converters ('mappings') as required.

As for the underlying type of `Date`'s and timestamps, that's because `R` is a extremely 'loosely type language'. I can have `double` type `Date`'s:

``` r
date <- as.Date(c("2016-01-02", "2014-01-02", "2012-01-02", "2017-01-02"))
typeof(date)
#> [1] "double"
print(date)
#> [1] "2016-01-02" "2014-01-02" "2012-01-02" "2017-01-02"
```

and convert the underlying type to `integer` and everything will just work:

``` r
mode(date) <- "integer"
typeof(date)
#> [1] "integer"
print(date)
#> [1] "2016-01-02" "2014-01-02" "2012-01-02" "2017-01-02"
```

So that's a nice challenge for a serialization framework :-). Same holds for timestamps  (`POSIXct` type in `R`), the `difftime` class any many others. Perhaps with custom converters, the conversions can be adapted to a specific language's needs, but the heavy lifting can be done from the Arrow side.

Having a shared memory 'Arrow table' would be awesome. You could operate on that table using the best (analytic) features of multiple languages (e.g. from a single script in Anaconda).

Thanks a lot for all the hard work!

**Comment by wesm** [comment]
What you're describing is all work that should be part of the R-Arrow bindings. For the pandas-Arrow glue, we have implemented an extra layer of schema metadata so that we can accommodate particular pandas-specific details so we have a mitigation strategy in the event of some ambiguity (e.g. te Parquet format has less metadata than pandas needs, so we store the schema as additional metadata http://pandas-docs.github.io/pandas-docs-travis/developer.html#storing-pandas-dataframe-objects-in-apache-parquet-format).

In the R serialization layer, if you wish to store double-timestamps as is without indicating that they are timestamps to other Arrow consumers (so if another libraries sees the data it will look like doubles), you could do this using custom metadata so that the data can be faithfully roundtripped without extra conversions.

**Comment by MarcusKlik** [comment]
Thanks @wesm for sharing your insights. So if you want to mark a column explicitly as a timestamp (cross-language) , conversion is the way to go.

greetings,
Mark

**Comment by wesm** [comment]
Closing as this is all handled in the `arrow` R library now. We will make the `feather` package use `arrow` in the somewhat near future
