### ISSUE TITLE
Feather current state / future?

### ISSUE THREAD

**Issue by kevbutler** [wesm/feather#318]
Wes, feel free to point me somewhere else if this is the wrong forum for this. I'm intrigued with Feather and Arrow and am curious as to where things stand right now. Particularly in light of these comments:

> As time has passed, as one might expect, quite a bit of code overlap has developed between Feather's C++ and Python components and Apache Arrow's respective C++ and Python libraries. To address this, I'm planning to merge the Feather implementation into the Arrow codebase, which will enable me to provide better performance and new features to Feather users. ([Source](http://wesmckinney.com/blog/outlook-for-2017/).)

> Feather is not designed for long-term data storage. At this time, we do not guarantee that the file format will be stable across versions. Instead, use Feather for quickly exchanging data between Python and R code, or for short-term storage of data frames as part of some analysis. ([Source](https://blog.cloudera.com/blog/2016/03/feather-a-fast-on-disk-format-for-data-frames-for-r-and-python-powered-by-apache-arrow/).)

I'm transitioning to Python / Pandas (from SAS and Stata) and really like the performance and interoperability aspects of Arrow and Feather. Is it still too early for me to rely on either for long-term storage? Also, it sounds like Feather is being deprecated. If I'm just getting started with both, should I be focused on Arrow?

Appreciate your thoughts as well as everything you've put into developing this!

**Comment by gansanay** [comment]
Hi!

Wes is the one person that can answer your questions, but let me give you some ideas as a fellow pandas user. First, that's a great thing to transition to python/pandas! It has saved me hundreds of hours I would have spent in other contexts.

Concerning your questions:
* Arrow is an in-memory format, Feather is the corresponding file format.
* Since Wes wrote what you quoted first, the Python Feather implementation was moved to the Arrow codebase. A look at the python source code in the Feather repository will convince you. The work that lies ahead is about the R bindings and some Feather C++ code for it, which is still here. I have started getting into the Arrow C++ sources and design docs in order to attempt a first try at Rcpp bindings but it's hard for me these days to spend time on it. The future is a very light Feather!
* Arrow evolves very fast and the format is then still subject to change, which means you can definitely use it for short term storage (like moving dataframes to and from R!), but you shouldn't rely on it for long-term storage, at least for now.

You should definitely continue your transition to python/pandas while keeping an eye on Arrow and pandas2, so you'll be among the early adopters!

To get more insight in the future of Arrow and pandas, I invite you to read the latest blog post by Wes: http://wesmckinney.com/blog/apache-arrow-pandas-internals/

Looking forward to your next issues and PRs, welcome onboard!

**Comment by ChristianSauer** [comment]
What I would like to know if there is some stable format, which can be used for storage?
Currently, we are still flinging around CSVs or xlsx files, but that has a lot of drawbacks.

**Comment by wesm** [comment]
@ChristianSauer I might recommend Parquet files for long-shelf-life data

**Comment by wesm** [comment]
See http://wesmckinney.com/blog/feather-arrow-future/ for a summary of where things are going
