### ISSUE TITLE
perf: interesting results

### ISSUE THREAD

**Issue by jreback** [wesm/feather#60]
pandas 0.18.0 / feather a58e3bef81c810091a081eb899961a7475b62dfc

mixed types

```
In [1]: df = pd.DataFrame({'A' : np.random.randn(1000000)})

In [2]: df['B'] = 'foo'

In [3]: df['C'] = pd.Timestamp('20130101')

In [4]: %timeit df.to_hdf('foo.h5', 'df')
1 loop, best of 3: 803 ms per loop

In [5]: %timeit pd.read_hdf('foo.h5', 'df')
1 loop, best of 3: 319 ms per loop

In [6]: import feather

In [7]: %timeit feather.write_dataframe(df, 'foo.fth')
10 loops, best of 3: 62.2 ms per loop

In [8]: %timeit feather.read_dataframe('foo.fth')
10 loops, best of 3: 56.8 ms per loop

In [9]: !ls -ltr foo*
-rw-rw-r--  1 jreback  staff  72487885 Mar 29 23:49 foo.h5
-rw-rw-r--  1 jreback  staff  23000356 Mar 29 23:50 foo.fth

In [10]: %timeit df.to_msgpack('foo.pak')
10 loops, best of 3: 160 ms per loop

In [12]: %timeit pd.read_msgpack('foo.pak')
10 loops, best of 3: 79.8 ms per loop

In [13]: %timeit df.to_msgpack('foo.pak', compress='blosc')
10 loops, best of 3: 139 ms per loop

In [14]: %timeit pd.read_msgpack('foo.pak')
10 loops, best of 3: 72 ms per loop
```

Just floats

```
In [20]: %timeit feather.write_dataframe(df[['A']], 'foo.fth')
100 loops, best of 3: 14.8 ms per loop

In [21]: %timeit feather.read_dataframe('foo.fth')
100 loops, best of 3: 7.47 ms per loop

In [22]: %timeit df[['A']].to_hdf('foo.h5', 'df')
10 loops, best of 3: 34 ms per loop

In [23]: %timeit pd.read_hdf('foo.h5', 'df')
100 loops, best of 3: 9.17 ms per loop

In [24]: %timeit df[['A']].to_msgpack('foo.pak', compress='blosc')
10 loops, best of 3: 37.3 ms per loop

In [25]: %timeit pd.read_msgpack('foo.pak')
100 loops, best of 3: 9.39 ms per loop

In [29]: !ls -ltr foo*
-rw-rw-r--  1 jreback  staff   8000152 Mar 29 23:55 foo.fth
-rw-rw-r--  1 jreback  staff  64487821 Mar 29 23:55 foo.h5
-rw-rw-r--  1 jreback  staff   8000310 Mar 30 00:00 foo.pak
```

Just some ad-hoc perf tests. floats about similar (but better than HDF5, slightly better than msgpack). 
Interesting that feather is WAY faster on fixed length strings in HDF5. (Almost about 1/3 serialized size, which obviously makes writing faster). Note these are the same length strings.

These are _slightly_ non-comparable, as the pandas routines are serializeing the index as well (so doing 2x the work for floats and 1 1/3 more for HDF5/msgpack).

**Comment by wesm** [comment]
Interesting, thanks for looking through these. For strictly numeric data (and ignoring the indexes), I would expect HDF5 to be faster in general. Especially when there are NaN values -- if you add some NaNs then the performance will change because feather stores nulls in a bitmap per the Arrow spec, and there's some cost to reconstructing the pandas-specific null representation. But a nice part of using a bitmap for nulls is that other systems don't need to know about how pandas or R represent nulls in memory. 

For people just using Python, the immediate benefits of using Feather are not that pronounced when you look at all the work that's gone into binary serialization tools. The biggest use case I see value for pandas users is being able to easily switch between Python and R within a particular analysis (for example, Jupyter notebooks with side-by-side Python and R kernels)

**Comment by dragoljub** [comment]
How do categorical columns get stored in feather? If I have 10M rows by 100 columns of lower cardinality, will we be storing repeated values or just the codes? For some data domains we have found that dumping to pickle with categorical columns is most efficient.

**Comment by wesm** [comment]
The code and categories are stored separately. So inside the feather file, the categories just look like any other (though most likely much smaller) array -- so you should get the same kind of perf benefits here
