### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [wesm/feather#73]
Would you like to [replace any double quotes](https://github.com/wesm/feather/blob/694e15bba7d456790eafd6216e2354899fe65deb/cpp/src/feather/api.h#L18 "Check header file inclusion style.") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by wesm** [comment]
No, unless there is some problem with using double quotes in header files associated with feather

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by wesm** [comment]
I'm afraid I still don't see the problem, or at least your argument is not clear. My understanding is that using double quotes for headers that are internal to a particular project is the best practice. 

Also, I have just scanned through your other reported issues on GitHub, and I find your public behavior to be extremely trollish. I strongly encourage you to change the way you are interacting with open source projects and to engage in a way that is more helpful (by explaining problems clearly, rather than posting links to things to read, or writing patches). If you continue to do it here, I will report abuse with GitHub. Thank you
